version: "3"

services: 
  db:
    image: postgres:14.0-alpine
    container_name: dbl
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - l0
  nats-str:
    image: nats-streaming:0.25.5
    restart: unless-stopped
    container_name: nats
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - l0
  app:
    build: .
    container_name: app
    restart: unless-stopped
    depends_on:
      - db
      - nats-str
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - l0
networks:
  l0:
